/** Declaration file generated by dts-gen */

export = ux4terminallogger;

declare const ux4terminallogger: {
    Font: {
        bg_blue: string;
        bg_cyan: string;
        bg_green: string;
        bg_magenta: string;
        bg_red: string;
        bg_white: string;
        bg_yellow: string;
        bold_off: string;
        bold_on: string;
        cls: string;
        fg_black: string;
        fg_blue: string;
        fg_cyan: string;
        fg_green: string;
        fg_magenta: string;
        fg_red: string;
        fg_white: string;
        fg_yellow: string;
        inverse_on: string;
        moveback1char: string;
        moveback1line: string;
        reset: string;
    };
    Log: {
        applyStyle: any;
        cls: any;
        debug: any;
        disableColor: any;
        fail: any;
        info: any;
        lf: any;
        majorError: any;
        showDebug: boolean;
        success: any;
        title: any;
        warn: any;
    };
};

